### ISSUE TITLE
Add support for typescript, jsx, and tsx

### ISSUE THREAD

**Issue by SCLeoX** [FractalBrew/vscode-backticks#1]

**Comment by Mossop** [comment]
It should be as simple as modifying the check here: https://github.com/FractalBrew/vscode-backticks/blob/master/extension.js#L6

If you feel like trying your hand at doing that I'd be happy to answer questions otherwise I'll take a look in a day or two.

**Comment by SCLeoX** [comment]
I tested it locally and it worked. #2 I am not sure if there is anything else should be tested.

**Comment by Mossop** [comment]
Fixed by a0430776aa2854ca4f395357d42a5bce3b6dbaa2
