### ISSUE TITLE
Cannot type "{" anywhere else

### ISSUE THREAD

**Issue by SCLeoX** [FractalBrew/vscode-backticks#5]
I cannot type this character in the search panel nor the command panel. When I hit the key, the "{" appeared in the editor instead of the input field I was on.

**Comment by Mossop** [comment]
Oof, good catch. I've pushed out a 1.2.0 with the fix for this, thanks for spotting it.

**Comment by SCLeoX** [comment]
I can confirm it is working now. Thanks!
